### PR TITLE
New hotend, update hotend, and update heatset

### PR DESCRIPTION
**Pull request by stackingdeezlayers**
just look at the commits kekw

### CODE REVIEW

**Comment by stackingdeezlayers** [comment]
Also, I messed up by not making these changes in another branch, but I suck at github. My bad. It'll work

**Comment by kyleisah** [comment]
Hey, just taking a look at these now. 

- Goliath
    - The newer goliath looks good but will require a little bit of tweaking. The nozzle isn't aligned to the origin point like the other hotend models are, and some of the components are missing. The nichrome wires from the heater element are combined to the sock component, but you do have quite a few advantages in this model. I think I can work these all together and update the PR.

- NexG
    - Origin is in the wrong spot, but the models are great quality. I think it makes the most sense to combine the UHF and HF models into one assembly and be able to toggle visibility for whatever model you have. But this looks pretty decent.

The "mass accurate" stuff is a new thing for me. Personally I don't really care if something in CAD is mass accurate or not, but I understand the appeal. Problem with that is, if you import it in .STEP format, the material isn't carried with it. This is probably something I can monitor a little closer when working on these things.

All that said, I do appreciate the PR, and welcome the additions, just gotta update them with some small tweaks and we're all set.

If you want to do the work, that'd really be appreciated. But if you want me to handle it, I can, it just might be a little bit before I get around to it.

**Comment by stackingdeezlayers** [comment]
Hey @kyleisah, I really appreciate the feedback.

> * Goliath
>   
>   * The newer goliath looks good but will require a little bit of tweaking. The nozzle isn't aligned to the origin point like the other hotend models are, and some of the components are missing. The nichrome wires from the heater element are combined to the sock component, but you do have quite a few advantages in this model. I think I can work these all together and update the PR.
> * NexG
>   
>   * Origin is in the wrong spot, but the models are great quality. I think it makes the most sense to combine the UHF and HF models into one assembly and be able to toggle visibility for whatever model you have. But this looks pretty decent

I realized I didn't place the hotends on the origin earlier today, and I told myself I'd do it later when I got to my computer. I definitely will now. In regards to the goliath model, I will take a look and try to fix that. It really should not be too hard.

> The "mass accurate" stuff is a new thing for me. Personally I don't really care if something in CAD is mass accurate or not, but I understand the appeal. Problem with that is, if you import it in .STEP format, the material isn't carried with it. This is probably something I can monitor a little closer when working on these things.

As for the heatset, I said something to hartk about the .step stuff yesterday right as I submitted the PR. Here is exactly what I said: 

> Just the density. That's why I changed the f3d and not the step. Step files seem to just kind of ignore everything related to the files "physical material".

 I don't really see a downside to having the weight be correct, but if you want, I can just delete this commit from the PR (maybe if I can even figure out how). It's definitely not necessary to have the right weight, but I like knowing the center of mass on printer parts I design, so having the heatsets being correct is necessary. I think others like me would also appreciate that

If there is anything else you would like to discuss about the PR, you can either comment here or DM me on discord (stackingdeezlayers). Thanks!

**Comment by stackingdeezlayers** [comment]
So much borked stuff..I'll fix eventually

**Pull request closed without merging**
